### PR TITLE
Add inspections for sass files (refs #5)

### PR DESCRIPTION
**Pull request by mruoss**
See issue #5 for the background info.

### CODE REVIEW

**Comment by Grawl** [comment]
How to install a plugin from your repo?

Want to test but got an error:

> Cannot Load Project
> com.intellij.ide.plugins.PluginManager$StartupAbortedExceptio…
>  Fatal error initializing plugin com.wix.sasslint



I just downloaded zip from your repo and install it as a plugin using “install plugin from disk”.

**Comment by mruoss** [comment]
I don't know, actually. I just located the plugin on the file system and replaced. ;)

**Comment by Grawl** [comment]
How do you edited the plugin on your system? In Mac, I am found it in `~/Library/Application Support/IntelliJIdea2017.3/sass-lint-plugin/lib/sass-lint-plugin.jar/META-INF/plugin.xml`. I am using [`mc`](https://midnight-commander.org) to edit file inside of an archive.

It works, great!

Next, I downloaded an archive from [JetBrains Plugins repository](https://plugins.jetbrains.com/plugin/8171-sass-lint) and edit it, so I can share your commit with my team.

Here it is: [sass-lint-plugin.zip](https://github.com/idok/sass-lint-plugin/files/1386016/sass-lint-plugin.zip) v1.0.6 with this PR edits

**Comment by Grawl** [comment]
hooray!

**Comment by mruoss** [comment]
:+1: Thanks.

**Comment by idok** [comment]
Sure, sorry for the late response and thanks for the contribution

**Pull request merged**
